### ISSUE TITLE
etcdenv doesn't exit when a process exits when watching

### ISSUE THREAD

**Issue by cameronmaske** [upfluence/etcdenv#4]
This is using 0.1.3

Example of interaction

```
etcdenv --namespace /env/prod/ echo "hi"
```

After echoing out "hi" etcdenv keeps the process alive, waiting for keys. 
Since this isn't a long running process, would it make sense for etcdenv to exit with it's sub process? 

The same is true for unsuccessful processes, e.g.

```
etcdenv --namespace /env/prod/ nosuchprocessshouldraiseanerror
```

**Comment by AlexisMontagne** [comment]
Hey @cameronmaske, 

if you want to execute a not long-running command, please use the `-r` option as:

```
etcdenv --namespace /env/prod/ -r echo "hi"
```

The options in the README are not well explained, i'll improve it soon.

**Comment by cameronmaske** [comment]
@AlexisMontagne Does "-r" still watch etcd keys for changes?

**Comment by cameronmaske** [comment]
@AlexisMontagne I don't think I've done a good job explaining.
This isn't just for non long running commands. 
If a process raises an exception after a certain time and exits, (e.g. a web server crashes) that exit code is not propagated outside of the etcdenv wrapper while watching the keys.
The reason this is useful, is I'm attempting to use etcdenv with process supervisor, so seeing a process has died or exited is required to restart it.  

A fake example of long running is like so...

```
etcdenv --namespace /env/prod/ "sleep 500; bad"
```

`sleep` in this case is a long running process (e.g. it could be a web server) but after 500 seconds it raises an exception and should exit. I'd expect etcdenv to exit with it. 
Is that a bit clearer?

**Comment by AlexisMontagne** [comment]
Yes it's clear, it could be useful to add this feature to etcdenv! 

I've seen you forked the repo, would you implement this feature? Otherwise, i will implement it in the next release.

**Comment by cameronmaske** [comment]
@AlexisMontagne I made a rough attempt at it! I'm not too familiar with Go, so this just currently exits on any code, rather then only on non zeros. https://github.com/cameronmaske/etcdenv/commit/3c080660adfde7555bf7d3ede561881c1f5c28d7

I'm sure someone with more Go experience would have a much better implementation.

**Comment by AlexisMontagne** [comment]
Hey @cameronmaske,

I just implemented and released a new version of etcdenv with the modification you asked for. 
Here is the modification https://github.com/upfluence/etcdenv/commit/9b6df65b0e39e996179a02fe0929506fb2c19a77. 

Now `etcdenv -n / -r bash -c "sleep 2; foo"` exits with the status 127 (status returned by `bash -c "sleep 2; foo"`)

Please, let me know if it satisfies you.

**Comment by cameronmaske** [comment]
@AlexisMontagne Fantastic stuff! thanks :D
